

export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Bmw',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '23.05.2021',
        updateDate: '24.05.2024',
        email: 'josen@doe.com',
        status: 'published',
        price: '200',
        phone: '123432567',
        location: 'Texas',
        image: 'https://images.pexels.com/photos/5976660/pexels-photo-5976660.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      },
      {
        id: '2',
        title: 'Audi',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '21.05.2021',
        updateDate: '23.05.2024',
        email: 'woj@mel.com',
        status: 'closed',
        price: '300',
        phone: '765098234',
        location: 'Colorado',
        image: 'https://images.pexels.com/photos/3221163/pexels-photo-3221163.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '3',
        title: 'Fiat',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '11.05.2021',
        updateDate: '13.05.2024',
        email: 'kas@gfd.com',
        status: 'published',
        price: '400',
        phone: '456098234',
        location: 'Cincinnati',
        image: 'https://images.pexels.com/photos/2218913/pexels-photo-2218913.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      },
      {
        id: '4',
        title: 'Opel',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '01.05.2021',
        updateDate: '03.05.2024',
        email: 'dam@tre.com',
        status: 'published',
        price: '500',
        phone: '096098234',
        location: 'NewYork',
        image: 'https://images.pexels.com/photos/9858907/pexels-photo-9858907.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '5',
        title: 'Toyota',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '15.04.2021',
        updateDate: '13.04.2024',
        email: 'hgf@ljk.com',
        status: 'published',
        price: '600',
        phone: '321098234',
        location: 'Berlin',
        image: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
      {
        id: '6',
        title: 'Nissan',
        content: 'Lorem ipsmum fadva sdqwdnapc apwoda mp wadn',
        publicationDate: '15.02.2021',
        updateDate: '13.02.2024',
        email: 'cvb@lkj.com',
        status: 'published',
        price: '700',
        phone: '678654123',
        location: 'Madryt',
        image: 'https://images.pexels.com/photos/919073/pexels-photo-919073.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: {
    active: true,
  },
};
